port: 7890
socks-port: 7891
redir-port: 0
allow-lan: false
mode: Rule
log-level: info
external-controller: '0.0.0.0:9090'
secret: ''
Proxy:
- { name: "极游官网jiyou.cloud",type: vmess,server: 114.114.114.114,port: 80,uuid: B2173CC6-75BD-B002-C2AC-64AB8CFECD1D,alterId: 0,cipher: auto, network: ws}
- { name: "极游B-JP-I",type: vmess,server: bjpa.zhileshu.com,port: 443,uuid: B2173CC6-75BD-B002-C2AC-64AB8CFECD1D,alterId: 0,cipher: auto, network: ws, ws-headers: { Host: bjpa.zhileshu.com }, tls: true}
- { name: "极游B-JP-II",type: vmess,server: bjpa.zhileshu.com,port: 443,uuid: B2173CC6-75BD-B002-C2AC-64AB8CFECD1D,alterId: 0,cipher: auto, network: ws, ws-headers: { Host: bjpb.zhileshu.com }, tls: true}
- { name: "极游B-HK",type: vmess,server: itunes.apple.com.ajax.microsoft.com.www.bing.com.hkt08.zhileshu.com,port: 443,uuid: B2173CC6-75BD-B002-C2AC-64AB8CFECD1D,alterId: 0,cipher: auto, network: ws, ws-headers: { Host: itunes.apple.com.ajax.microsoft.com.www.bing.com.hkt08.zhileshu.com }, tls: true}
- { name: "极游B-SG",type: vmess,server: b-sg.zhileshu.com,port: 443,uuid: B2173CC6-75BD-B002-C2AC-64AB8CFECD1D,alterId: 0,cipher: auto, network: ws, ws-headers: { Host: b-sg.zhileshu.com }, tls: true}

Proxy Group:
#- { name: AIR B, type: select, proxies: ["极游官网jiyou.cloud", "极游B-JP-I", "极游B-JP-II", "极游B-HK", "极游B-SG"]}
- { name: auto, type: url-test, proxies: ["极游官网jiyou.cloud", "极游B-JP-I", "极游B-JP-II", "极游B-HK", "极游B-SG"], url: http://www.gstatic.com/generate_204, interval: 300 }
#- { name: fallback, type: fallback, proxies: ["极游官网jiyou.cloud", "极游B-JP-I", "极游B-JP-II", "极游B-HK", "极游B-SG"], url: http://www.gstatic.com/generate_204, interval: 300 }
Rule:
- DOMAIN-SUFFIX,google.com,AIR B
- DOMAIN-KEYWORD,google,AIR B
- DOMAIN,google.com,AIR B
- DOMAIN-SUFFIX,ad.com,REJECT
- IP-CIDR,127.0.0.0/8,DIRECT
- GEOIP,CN,DIRECT
- MATCH,AIR B
